<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Search'), '<span class="zf-green">', '</span>') ?></h1>
    <a href="http://46.101.40.23/jeuxdemots/public/"> http://46.101.40.23/jeuxdemots/public/ </a>
    <p> Pour l'instant il n'y pas de connection à la base de donnés dans le serveur. </p>
</div>

<div class="row">

    <div class="col-md-12">
        sasasa
    </div>
    
    
</div>
