/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from 'ng2-completer/ng2-completer.module';
import * as import9 from 'ng2-page-scroll/src/ng2-page-scroll.module';
import * as import10 from 'ng2-popover/index';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/animation/animation_queue';
import * as import22 from '@angular/core/src/linker/view_utils';
import * as import23 from '@angular/platform-browser/src/browser/title';
import * as import24 from '@angular/http/src/backends/browser_xhr';
import * as import25 from '@angular/http/src/base_response_options';
import * as import26 from '@angular/http/src/backends/xhr_backend';
import * as import27 from '@angular/http/src/base_request_options';
import * as import28 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import29 from 'ng2-completer/services/completer-service';
import * as import30 from '../../app/word.service';
import * as import31 from '@angular/core/src/di/injector';
import * as import32 from '../node_modules/ng2-popover/PopoverContent.ngfactory';
import * as import33 from './app.component.ngfactory';
import * as import34 from '@angular/core/src/i18n/tokens';
import * as import35 from '@angular/core/src/application_tokens';
import * as import36 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import37 from '@angular/platform-browser/src/dom/events/key_events';
import * as import38 from '@angular/core/src/zone/ng_zone';
import * as import39 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import40 from 'ng2-completer/services/completer-data-factory';
import * as import41 from '@angular/core/src/console';
import * as import42 from '@angular/core/src/error_handler';
import * as import43 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import44 from '@angular/platform-browser/src/dom/animation_driver';
import * as import45 from '@angular/core/src/render/api';
import * as import46 from '@angular/core/src/security';
import * as import47 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import48 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import49 from '@angular/http/src/interfaces';
import * as import50 from '@angular/http/src/http';
import * as import51 from 'ng2-completer/services/local-data';
import * as import52 from 'ng2-completer/services/remote-data';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _Ng2CompleterModule_6:import8.Ng2CompleterModule;
  _Ng2PageScrollModule_7:import9.Ng2PageScrollModule;
  _PopoverModule_8:import10.PopoverModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import11.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ApplicationInitStatus_13:import12.ApplicationInitStatus;
  _Testability_14:import13.Testability;
  _ApplicationRef__15:import14.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import15.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import16.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import17.EventManager;
  __DomSharedStylesHost_23:import18.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import19.DomRootRenderer_;
  __RootRenderer_26:any;
  __DomSanitizer_27:import20.DomSanitizerImpl;
  __Sanitizer_28:any;
  __AnimationQueue_29:import21.AnimationQueue;
  __ViewUtils_30:import22.ViewUtils;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __SharedStylesHost_33:any;
  __Title_34:import23.Title;
  __BrowserXhr_35:import24.BrowserXhr;
  __ResponseOptions_36:import25.BaseResponseOptions;
  __XSRFStrategy_37:any;
  __XHRBackend_38:import26.XHRBackend;
  __RequestOptions_39:import27.BaseRequestOptions;
  __Http_40:any;
  __RadioControlRegistry_41:import28.RadioControlRegistry;
  __LocalData_42:any;
  __RemoteData_43:any;
  __CompleterService_44:import29.CompleterService;
  __WordService_45:import30.WordService;
  constructor(parent:import31.Injector) {
    super(parent,[
      import32.PopoverContentNgFactory,
      import33.AppComponentNgFactory
    ]
    ,[import33.AppComponentNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == null)) { (this.__LOCALE_ID_10 = import3._localeFactory(this.parent.get(import34.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == null)) { (this.__NgLocalization_11 = new import11.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == null)) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import15.Compiler {
    if ((this.__Compiler_17 == null)) { (this.__Compiler_17 = new import15.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == null)) { (this.__APP_ID_18 = import35._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == null)) { (this.__DOCUMENT_19 = import4._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import16.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == null)) { (this.__HAMMER_GESTURE_CONFIG_20 = new import16.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == null)) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import36.DomEventsPlugin(),
      new import37.KeyEventsPlugin(),
      new import16.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import17.EventManager {
    if ((this.__EventManager_22 == null)) { (this.__EventManager_22 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import38.NgZone))); }
    return this.__EventManager_22;
  }
  get _DomSharedStylesHost_23():import18.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_23 == null)) { (this.__DomSharedStylesHost_23 = new import18.DomSharedStylesHost(this._DOCUMENT_19)); }
    return this.__DomSharedStylesHost_23;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == null)) { (this.__AnimationDriver_24 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == null)) { (this.__DomRootRenderer_25 = new import19.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24,this._APP_ID_18)); }
    return this.__DomRootRenderer_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == null)) { (this.__RootRenderer_26 = import39._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import39.NgProbeToken,(null as any)),this.parent.get(import14.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == null)) { (this.__DomSanitizer_27 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == null)) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _AnimationQueue_29():import21.AnimationQueue {
    if ((this.__AnimationQueue_29 == null)) { (this.__AnimationQueue_29 = new import21.AnimationQueue(this.parent.get(import38.NgZone))); }
    return this.__AnimationQueue_29;
  }
  get _ViewUtils_30():import22.ViewUtils {
    if ((this.__ViewUtils_30 == null)) { (this.__ViewUtils_30 = new import22.ViewUtils(this._RootRenderer_26,this._Sanitizer_28,this._AnimationQueue_29)); }
    return this.__ViewUtils_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == null)) { (this.__IterableDiffers_31 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == null)) { (this.__KeyValueDiffers_32 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_32;
  }
  get _SharedStylesHost_33():any {
    if ((this.__SharedStylesHost_33 == null)) { (this.__SharedStylesHost_33 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_33;
  }
  get _Title_34():import23.Title {
    if ((this.__Title_34 == null)) { (this.__Title_34 = new import23.Title()); }
    return this.__Title_34;
  }
  get _BrowserXhr_35():import24.BrowserXhr {
    if ((this.__BrowserXhr_35 == null)) { (this.__BrowserXhr_35 = new import24.BrowserXhr()); }
    return this.__BrowserXhr_35;
  }
  get _ResponseOptions_36():import25.BaseResponseOptions {
    if ((this.__ResponseOptions_36 == null)) { (this.__ResponseOptions_36 = new import25.BaseResponseOptions()); }
    return this.__ResponseOptions_36;
  }
  get _XSRFStrategy_37():any {
    if ((this.__XSRFStrategy_37 == null)) { (this.__XSRFStrategy_37 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_37;
  }
  get _XHRBackend_38():import26.XHRBackend {
    if ((this.__XHRBackend_38 == null)) { (this.__XHRBackend_38 = new import26.XHRBackend(this._BrowserXhr_35,this._ResponseOptions_36,this._XSRFStrategy_37)); }
    return this.__XHRBackend_38;
  }
  get _RequestOptions_39():import27.BaseRequestOptions {
    if ((this.__RequestOptions_39 == null)) { (this.__RequestOptions_39 = new import27.BaseRequestOptions()); }
    return this.__RequestOptions_39;
  }
  get _Http_40():any {
    if ((this.__Http_40 == null)) { (this.__Http_40 = import5.httpFactory(this._XHRBackend_38,this._RequestOptions_39)); }
    return this.__Http_40;
  }
  get _RadioControlRegistry_41():import28.RadioControlRegistry {
    if ((this.__RadioControlRegistry_41 == null)) { (this.__RadioControlRegistry_41 = new import28.RadioControlRegistry()); }
    return this.__RadioControlRegistry_41;
  }
  get _LocalData_42():any {
    if ((this.__LocalData_42 == null)) { (this.__LocalData_42 = import40.localDataFactory()); }
    return this.__LocalData_42;
  }
  get _RemoteData_43():any {
    if ((this.__RemoteData_43 == null)) { (this.__RemoteData_43 = import40.remoteDataFactory(this._Http_40)); }
    return this.__RemoteData_43;
  }
  get _CompleterService_44():import29.CompleterService {
    if ((this.__CompleterService_44 == null)) { (this.__CompleterService_44 = new import29.CompleterService(this._LocalData_42,this._RemoteData_43)); }
    return this.__CompleterService_44;
  }
  get _WordService_45():import30.WordService {
    if ((this.__WordService_45 == null)) { (this.__WordService_45 = new import30.WordService(this._Http_40)); }
    return this.__WordService_45;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._Ng2CompleterModule_6 = new import8.Ng2CompleterModule();
    this._Ng2PageScrollModule_7 = new import9.Ng2PageScrollModule();
    this._PopoverModule_8 = new import10.PopoverModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ApplicationInitStatus_13 = new import12.ApplicationInitStatus(this.parent.get(import12.APP_INITIALIZER,(null as any)));
    this._Testability_14 = new import13.Testability(this.parent.get(import38.NgZone));
    this._ApplicationRef__15 = new import14.ApplicationRef_(this.parent.get(import38.NgZone),this.parent.get(import41.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_13,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_14);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import8.Ng2CompleterModule)) { return this._Ng2CompleterModule_6; }
    if ((token === import9.Ng2PageScrollModule)) { return this._Ng2PageScrollModule_7; }
    if ((token === import10.PopoverModule)) { return this._PopoverModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import34.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import42.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import13.Testability)) { return this._Testability_14; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import15.Compiler)) { return this._Compiler_17; }
    if ((token === import35.APP_ID)) { return this._APP_ID_18; }
    if ((token === import43.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import17.EventManager)) { return this._EventManager_22; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import44.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import45.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import46.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import21.AnimationQueue)) { return this._AnimationQueue_29; }
    if ((token === import22.ViewUtils)) { return this._ViewUtils_30; }
    if ((token === import47.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import48.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_33; }
    if ((token === import23.Title)) { return this._Title_34; }
    if ((token === import24.BrowserXhr)) { return this._BrowserXhr_35; }
    if ((token === import25.ResponseOptions)) { return this._ResponseOptions_36; }
    if ((token === import49.XSRFStrategy)) { return this._XSRFStrategy_37; }
    if ((token === import26.XHRBackend)) { return this._XHRBackend_38; }
    if ((token === import27.RequestOptions)) { return this._RequestOptions_39; }
    if ((token === import50.Http)) { return this._Http_40; }
    if ((token === import28.RadioControlRegistry)) { return this._RadioControlRegistry_41; }
    if ((token === import51.LocalData)) { return this._LocalData_42; }
    if ((token === import52.RemoteData)) { return this._RemoteData_43; }
    if ((token === import29.CompleterService)) { return this._CompleterService_44; }
    if ((token === import30.WordService)) { return this._WordService_45; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);