/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/word.service';
import * as import9 from '../node_modules/ng2-page-scroll/src/ng2-page-scroll.directive.ngfactory';
import * as import10 from '../../app/search-word-component';
import * as import11 from './search-word-component.ngfactory';
import * as import12 from 'ng2-page-scroll/src/ng2-page-scroll.service';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import15 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import16 from 'ng2-completer/services/completer-service';
import * as import17 from '@angular/http/src/http';
import * as import18 from 'ng2-page-scroll/src/ng2-page-scroll.directive';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.WordService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AppComponent_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _PageScroll_0_3:import9.Wrapper_PageScroll;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  compView_36:import1.AppView<import10.SearchWordComponet>;
  _SearchWordComponet_36_3:import11.Wrapper_SearchWordComponet;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'i',new import3.InlineArray8(6,'class','iconTop fa fa-arrow-up','href','#search-word-section','pageScroll',''),(null as any));
    this._PageScroll_0_3 = new import9.Wrapper_PageScroll(this.parentView.injectorGet(import12.PageScrollService,this.parentIndex),this.parentView.injectorGet(import13.Router,this.parentIndex,(null as any)),this.parentView.injectorGet(import14.DOCUMENT,this.parentIndex));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container body'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','main_container'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','top_nav navbar navbar-fixed-top'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','nav_menu'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'nav',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray4(4,'class','nav toggle','style','width: 20%'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n              ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'a',new import3.InlineArray2(2,'id','menu_toggle'),(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'i',new import3.InlineArray2(2,'class','fa fa-bars'),(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray4(4,'class','text-center','style','display: inline-table; width: 60%'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n            	',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'a',new import3.InlineArray4(4,'class','site_title','href','/'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,' ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Dictionnaire de mots',(null as any));
    this._text_27 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_13,'ul',new import3.InlineArray4(4,'class','nav navbar-nav navbar-right','style','width: 20%'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n              \n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_13,'\n          ',(null as any));
    this._text_32 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_34 = this.renderer.createText(this._el_4,'\n      	',(null as any));
    this._text_35 = this.renderer.createText(this._el_4,'\n		\n		',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_4,'search-word-component',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_36 = new import11.View_SearchWordComponet0(this.viewUtils,this,36,this._el_36);
    this._SearchWordComponet_36_3 = new import11.Wrapper_SearchWordComponet(this.parentView.injectorGet(import12.PageScrollService,this.parentIndex),this.parentView.injectorGet(import14.DOCUMENT,this.parentIndex),this.parentView.injectorGet(import8.WordService,this.parentIndex),this.parentView.injectorGet(import15.DomSanitizer,this.parentIndex),this.parentView.injectorGet(import16.CompleterService,this.parentIndex),this.parentView.injectorGet(import17.Http,this.parentIndex));
    this.compView_36.create(this._SearchWordComponet_36_3.context);
    this._text_37 = this.renderer.createText(this._el_4,'\n\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_4,'footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'div',new import3.InlineArray2(2,'class','pull-right'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'© 2016 - 2017 by Ikbal Hamdaoui - Jimmy Muñoz.',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_39,'div',new import3.InlineArray2(2,'class','clearfix'),(null as any));
    this._text_45 = this.renderer.createText(this._el_39,'\n    ',(null as any));
    this._text_46 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_47 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_48 = this.renderer.createText(this._el_2,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.PageScroll) && (0 === requestNodeIndex))) { return this._PageScroll_0_3.context; }
    if (((token === import10.SearchWordComponet) && (36 === requestNodeIndex))) { return this._SearchWordComponet_36_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = '#search-word-section';
    this._PageScroll_0_3.check_href(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = 60;
    this._PageScroll_0_3.check_pageScrollOffset(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = '';
    this._PageScroll_0_3.check_pageScroll(currVal_0_0_2,throwOnChange,false);
    this._PageScroll_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._SearchWordComponet_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    this.compView_36.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_36.destroy();
    this._PageScroll_0_3.ngOnDestroy();
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._PageScroll_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}