<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Jeux de Mots '. $this->translate('JdM -> Ikbal - Jimmy'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
              //->prependStylesheet($this->basePath('css/style.css'))
              //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
              //->prependStylesheet($this->basePath('css/bootstrap.min.css')) 

               //->prependStylesheet($this->basePath('template/build/css/custom.min.css'))
               ->prependStylesheet($this->basePath('template/build/css/custom.css'))
               //->prependStylesheet($this->basePath('template/vendors/jqvmap/dist/jqvmap.min.css'))
               //->prependStylesheet($this->basePath('template/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'))
               ->prependStylesheet($this->basePath('template/vendors/iCheck/skins/flat/green.css'))
               //->prependStylesheet($this->basePath('template/vendors/nprogress/nprogress.css'))
               ->prependStylesheet($this->basePath('template/vendors/font-awesome/css/font-awesome.min.css'))
               ->prependStylesheet($this->basePath('template/vendors/bootstrap/dist/css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('systemjs.config.js'))
            ->prependFile("https://unpkg.com/systemjs@0.19.27/dist/system.src.js")
            ->prependFile("https://unpkg.com/reflect-metadata@0.1.3")
            ->prependFile("https://unpkg.com/zone.js@0.6.25?main=browser")
            ->prependFile("https://unpkg.com/core-js/client/shim.min.js")
        ; ?>
        <script>
            System.import('app').catch(function(err){ console.error(err); });
        </script>

    </head>
    <body class="nav-md footer_fixed-">
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
        <!-- jQuery -->
        <script src="template/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="template/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->

        <!-- Custom Theme Scripts -->
        <script src="template/build/js/custom.min.js"></script>
        <script src="js/custom_jeux_de_mots.js"></script>
    </body>
</html>
