<!-- 
-->
<div>
  <my-app>Loading Angular 2...</my-app>
</div>
<div id="animation_content">
  <style>
  .animated_div_left {
      width:76px;
      height:47px;
      color: #92B901;
      position: fixed;
      font-weight:bold;
      font-size:30px;
      padding:10px;
      animation: animated_div_left 3s linear 0s infinite alternate;
       /*
      animation:animated_div_left 3s;
      animation-iteration-count: infinite;
       */
      -moz-animation:animated_div_left 3s linear 0s infinite alternate;
      -webkit-animation:animated_div_left 3s linear 0s infinite alternate;
      -o-animation:animated_div_left 3s linear 0s infinite alternate;
      border-radius:5px;
      -webkit-border-radius:5px;
  }

  @keyframes animated_div_left
  {
      0% {transform: rotate(0deg);right:50%;}
      25% {transform: rotate(20deg);right:50%;}
      50% {transform: rotate(360deg);right:80%;}
      55% {transform: rotate(0deg);right:80%;}
      70% {transform: rotate(0deg);right:80%;}
      100% {transform: rotate(-360deg);right:50%;}
  }

  .animated_div_right {
      width:76px;
      height:47px;
      color: #92B901;
      position: fixed;
      left:50%;
      font-weight:bold;
      font-size:30px;
      padding:10px;
      animation: animated_div_right 3s linear 0s infinite alternate;
       /*
      animation:animated_div_right 3s;
      animation-iteration-count: infinite;
       */
      -moz-animation:animated_div_right 3s linear 0s infinite alternate;
      -webkit-animation:animated_div_right 3s linear 0s infinite alternate;
      -o-animation:animated_div_right 3s linear 0s infinite alternate;
      border-radius:5px;
      -webkit-border-radius:5px;
  }

  @keyframes animated_div_right
  {
      0% {transform: rotate(0deg);left:50%;}
      25% {transform: rotate(20deg);left:50%;}
      50% {transform: rotate(360deg);left:70%;}
      55% {transform: rotate(0deg);left:70%;}
      70% {transform: rotate(0deg);left:70%;}
      100% {transform: rotate(-360deg);left:50%;}
  }

  /*
  @-webkit-keyframes animated_div
  {
      0% {-webkit-transform: rotate(0deg);left:0px;}
      25% {-webkit-transform: rotate(20deg);left:0px;}
      50% {-webkit-transform: rotate(0deg);left:500px;}
      55% {-webkit-transform: rotate(0deg);left:500px;}
      70% {-webkit-transform: rotate(0deg);left:500px;color:#1ec7e6;}
      100% {-webkit-transform: rotate(-360deg);left:0px;}
  }

  @-moz-keyframes animated_div
  {
  0%  {-moz-transform: rotate(0deg);left:0px;}
  25% {-moz-transform: rotate(20deg);left:0px;}
  50%  {-moz-transform: rotate(0deg);left:500px;}
  55%  {-moz-transform: rotate(0deg);left:500px;}
  70%  {-moz-transform: rotate(0deg);left:500px;color:#1ec7e6;}
  100% {-moz-transform: rotate(-360deg);left:0px;}
  }

  @-o-keyframes animated_div
  {
  0% {transform: rotate(0deg);left:0px;}
  25% {transform: rotate(20deg);left:0px;}
  50%  {transform: rotate(0deg);left:500px;}
  55%  {transform: rotate(0deg);left:500px;}
  70%  {transform: rotate(0deg);left:500px;color:#1ec7e6;}
  100% {transform: rotate(-360deg);left:0px;}
  }
  */


  </style>
  <div style="z-index: 2px; position: fixed; top: 50%; left: 50%;  ">
    <img src="images/book_img.png" alt="HTML5 Icon" style="width:200px; margin-top: -50px; margin-left: -100px;">
  </div>
  <div class="animated_div_left" style="font-size: 2em; top: 10%;color:#1a6ef6">Chat</div>
  <div class="animated_div_right" style="top: 10%;color:#dffba8">Profiter</div>
  <div class="animated_div_left" style="font-size: 1.5em; top: 20%; color:#a7ccc4">Échouer</div>
  <div class="animated_div_right" style="top: 20%; color: #ff2d39">Printemps</div>
  <div class="animated_div_left" style="top: 30%; color: #1b998a;">Chanson</div>
  <div class="animated_div_right" style="top: 35%; color: #CCCC00;">Copains</div>
  <div class="animated_div_left" style="font-size: 3em; top: 40%; color: #EF5184;">Amis</div>
  <div class="animated_div_right" style="top: 40%; color: #1ec7e6;">Fétefora</div>
  <div class="animated_div_left" style="top: 50%; color: #1ec7e6;">Chimie</div>
  <div class="animated_div_right" style="top: 50%; color: #e0c544;">Musique</div>
  <div class="animated_div_right" style="top: 60%; color: #ffb358;">SVT</div>
  <div class="animated_div_left" style="top: 65%; color: #7d8413;">Vélo</div>
  <div class="animated_div_right" style="top: 70%; color: #15CAB1;">Sports</div>
  <div class="animated_div_left" style="top: 70%; color: #00CCFF;">Réussir</div>
  <div class="animated_div_left" style="top: 80%; color: #FF6F00;">Natation</div>
  <div class="animated_div_right" style="top: 85%; left: 10%; color: #CCFF00;">Saisons</div>
</div>