<!-- 
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Jeux de Mots'), '<span class="zf-green">', '</span>') ?></h1>
    <a href="http://46.101.40.23/jeuxdemots/public/"> http://46.101.40.23/jeuxdemots/public/ </a>
    <p> Pour l'instant il n'y pas de connection à la base de donnés dans le serveur. </p>
</div>
-->
<a href="http://46.101.40.23/jeuxdemots/public/"> http://46.101.40.23/jeuxdemots/public/ </a>

<my-app>Loading Angular 2...</my-app>

<div class="x_content">
  <ul class="list-unstyled timeline">
    <li>
      
    </li>
    <li>
      <div class="block">
        <div class="tags">
          <a href="" class="tag">
            <span>Entertainment</span>
          </a>
        </div>
        <div class="block_content">
          <h2 class="title">
              <a>Who Needs Sundance When You’ve Got&nbsp;Crowdfunding?</a>
          </h2>
          <div class="byline">
            <span>13 hours ago</span> by <a>Jane Smith</a>
          </div>
          <p class="excerpt">Film festivals used to be do-or-die moments for movie makers. They were where you met the producers that could fund your project, and if the buyers liked your flick, they’d pay to Fast-forward and… <a>Read&nbsp;More</a>
          </p>
        </div>
      </div>
    </li>
    <li>
      <div class="block">
        <div class="tags">
          <a href="" class="tag">
            <span>Entertainment</span>
          </a>
        </div>
        <div class="block_content">
          <div class="x_panel">
              <div class="x_title">
                <h2>Tooltips <small>Hover to view</small></h2>
                <ul class="nav navbar-right panel_toolbox" style="min-width: 20px;">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">

                <p>Hover over the links below to see tooltips:</p>

              </div>
            </div>
        </div>
      </div>
    </li>
    <li>
      <div class="block">
        <div class="tags">
          <a href="" class="tag">
            <span>Entertainment</span>
          </a>
        </div>
        <div class="block_content">
            <div class="x_panel">
              <div class="x_title">
                <span>Entertainment</span> <small>Hover to view</small>
                <ul class="nav navbar-right pull-right">
                  <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">

                <p>Hover over the links below to see tooltips:</p>

              </div>
            </div>


        </div>
      </div>
    </li>
  </ul>

</div>

<div class="col-md-12 col-sm-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Tooltips <small>Hover to view</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">

        <p>Hover over the links below to see tooltips:</p>

      </div>
    </div>
  </div>
</div>
<!-- 
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Search Words (Angular2 - Typescript)') ?></h3>
            </div>
            <div class="panel-body">
               
            </div>
        </div>
              
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Architecture') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Notre architecture') ?>

                </p>
                <img src="img/general-architecture.png" style="width: 90%;" /> 
                
            </div>
        </div>
    </div> 
</div>
-->
