<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Jeux de Mots'), '<span class="zf-green">', '</span>') ?></h1>
    <a href="http://46.101.40.23/jeuxdemots/public/"> http://46.101.40.23/jeuxdemots/public/ </a>
    <p> Pour l'instant il n'y pas de connection à la base de donnés dans le serveur. </p>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Search Words (Angular2 - Typescript)') ?></h3>
            </div>
            <div class="panel-body">
                <my-app>Loading Angular 2...</my-app>
            </div>
        </div>
              
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Architecture') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $this->translate('Notre architecture') ?>

                </p>
                <img src="img/general-architecture.png" style="width: 90%;" /> 
                <!-- 
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
                -->
            </div>
        </div>
    </div>

    
</div>
